# Generated by Django 5.1.5 on 2025-02-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imdb_id", models.CharField(max_length=20, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("year", models.CharField(max_length=10)),
                ("rated", models.CharField(blank=True, max_length=10, null=True)),
                ("released", models.CharField(blank=True, max_length=50, null=True)),
                ("runtime", models.CharField(blank=True, max_length=50, null=True)),
                ("genre", models.CharField(blank=True, max_length=255, null=True)),
                ("director", models.CharField(blank=True, max_length=255, null=True)),
                ("actors", models.TextField(blank=True, null=True)),
                ("plot", models.TextField(blank=True, null=True)),
                ("language", models.CharField(blank=True, max_length=255, null=True)),
                ("country", models.CharField(blank=True, max_length=255, null=True)),
                ("awards", models.TextField(blank=True, null=True)),
                ("poster", models.URLField(blank=True, null=True)),
                ("imdb_rating", models.CharField(blank=True, max_length=10, null=True)),
                ("box_office", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
